### ISSUE TITLE
[FAQ] Nested shared folder safe with exclusion rule?

### ISSUE THREAD

**Issue by desbma** [syncthing/docs#428]
https://docs.syncthing.net/users/faq.html#am-i-able-to-nest-shared-folders-in-syncthing

> 2.2.12. Am I able to nest shared folders in Syncthing?
> Do not share a folder which is inside another shared folder. This behaviour is in no way supported, recommended or coded for in any way, and comes with many pitfalls.

I think the wording could be more nuanced here, because if the parent shared folder `/parent` has an exclusion rule for `/parent/child`, then I think it is safe to also have `/parent/child` as a separate shared folder.

Or I am missing something?

Edit: I am running a similar setup for more than a week now, and have not encountered any issues.

**Comment by kluppy** [comment]
"This behaviour is in no way supported, recommended or coded for in any way" is the important part.

I have nested folders that work well but when the file system watcher was implemented ST started crashing and loosing configuration.
Just because it currently works doesn't mean it won't break in the future.

I still have nested folders. I just can't use the FS watcher on those folders.

It should probably read:

This behaviour is not supported, recommended or coded for in any way, and comes with many pitfalls.

**Comment by desbma** [comment]
> I have nested folders that work well but when the file system watcher was implemented ST started crashing and loosing configuration.

Did you setup an ["ignore" rule](https://docs.syncthing.net/users/ignoring.html)  in the parent folder?

**Comment by kluppy** [comment]
No i don't but that isn't my point. The point is there are multiple ways to work around the issues but it is to hard to list them. The functionality is not supported so work arounds should not be documented in the official docs. Otherwise future code would be expected to allow for the documented work around to continue working.

**Comment by desbma** [comment]
My point is that setting up an ignore rule may is not a workaround, but a way to make both folders independent and therefore safe to use that way.

I don't see what could be unsafe, fragile, or require any special case in the Syncthing code for that setup, but I may have overlooked something, and in that case a developer can close that issue.

**Comment by calmh** [comment]
It's safe even in the absence of exclusions, as long as you avoid circular references. But there are caveats, like remote changes becoming local ones, which can make things difficult  to understand and troubleshoot. So yeah, some nuance could probably be added, but I'm not sure what it would be exactly.
