### ISSUE TITLE
small typo in File Versioning doc

### ISSUE THREAD

**Issue by imthenachoman** [syncthing/docs#599]
https://docs.syncthing.net/users/versioning.html has this at the top:

> Versioning applies to changes received from other devices. That is, if Alice has versioning turned on and Bob changes a file, the old version will be archived on Alice’s computer when that change is synced from Bob. If Alice changes a file locally on her own computer Syncthing will not and can not archive the old version.

The last line has a typo:

> If Alice changes a file locally on her own computer Syncthing will not and can not archive the old version.

I assume it means to say:

> If Alice changes a file locally on her own computer Syncthing will not **know** and can not archive the old version.

But I do not want to assume.

**Comment by imsodin** [comment]
I don't think that's a typo. It might not be the best of sentences, but the way I understand it, it is correct. To me it's basically a shorter version of "Syncthing will not archive the old version, and it cannot, because the old version is already gone at this point".

Anyway if you want to improve the wording, you are very welcome edit it and file a PR.
